### ISSUE TITLE
Header styling

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#12]
**Tasks**

- [x] Make hoover effects on the menu items
- [x] Put links to email and mobile fields
- [x] Make the telephone icon bigger
