### ISSUE TITLE
Designing the logo

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#13]
**Tasks**

- [ ] Create a white horizontal logo
- [ ] Create an orange horizontal logo
- [ ] Create a white vertical logo
- [ ] Create an orange vertical logo
