### ISSUE TITLE
Handle properly the state after confirming a reservation

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#25]
**Description**

Currently, after confirming a reservation all the data remains in the form and I don't get any information about my reservation.

**Tasks**

- [x] Redirect the user to the home page after reserving
- [x] Design a popup window that will appear after confirming the reservation in Figma
- [x] Show the previously designed popup window after the user clicks on the confirmation button
