### ISSUE TITLE
redesign calendars

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#28]
**Description**

Currently, it is hard to read the dates of the calendar and the colors are not that aesthetic.

**Tasks**

- [x] Make the numbers of the dates bold
- [x] Make the difference between disabled and not disabled dates more visible
- [x] Choose a better color for selected dates
