### ISSUE TITLE
Use cache during the reservation process

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#31]
**Description**

Right now during the reservation process I don't use cache, so if the user reloads the page all the already typed data will be lost and the process should be started all over again.

**Tasks**

- [ ] Save data to the cache every time the user enters new data
- [ ] Get the data that is necessary for the reservation process from the cache
- [ ] Delete the cache after reservation is confirmed
