### ISSUE TITLE
Reservation form error handling

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#32]
**Description**

Currently, if any error occurs I just show a general error message in a dialog box. The user won't know what is the error, what to do and will be confused.

**Tasks**

- [x] In the reservation form when something is not properly filled out show little notes under the form fields with easily understandable error messages
- [x] After clicking on confirmation button in the reservation form the above mentioned error messages should be shown and we should navigate the user to the proper page where the error occured
- [x] After clicking on confirmation button in the reservation form if the whole form is properly filled out and no error occurs in the backend the confirmation dialog should be showed otherwise an error message dialog.
