### ISSUE TITLE
Disable menu items if previous forms are invalid in registration form

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#38]
**Description**

Currently a reservation can be made without any requirements (e.g. with no data).

**Tasks**

- [x] If no date is selected disable all other steps
- [x] If dates are selected enable only the guests page
- [x] Once the guests page was visited enable data step
- [x] Once all the data has been filled out properly enable summery step
