### ISSUE TITLE
Set up development and production environments

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#51]
**Description**

Currently, there is only one database which is a huge problem as the application is going to be developed after deploying it once.

**Tasks**

- [x] Create a new database instance in the MongoDB Atlas
- [x] Save the credentials in environment variables
- [x] Use different database while developing and on production with the help of the environment variables
