### ISSUE TITLE
Required fields in reservation form don't work properly

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#53]
**Description**

After removing the guests component the stepper of the reservation form allows us to step to the next component even is the previous one was not valid. Also, the validation error texts are written under the fields with a relatively big padding so that the fields flow into the next button.

**Tasks**

- [x] Fix the bug
- [x] Imply with a (*) sign which fields are required
- [x] If a field has an error make it red instead of writing a text under it
