### ISSUE TITLE
Use dropdown menu when selecting number of adults and children

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#54]
**Description**

Currently we are using simple number inputs when selecting the number of adults and children. It is a huge effort to make safe validations for these fields. Also next to the other field inputs these seem really long and unaesthetic.

**Tasks**

- [x] Replace the input fields in case of selecting number of children and adults with a dropdown menu
- [x] Make the new input field look the same as a normal one
- [x] The options for the adult dropdown menu are from 1 to six in a format like "1 Felnőtt"
- [x] The options for selecting children are from 0 to 4 in a format like "1 Gyermek"
