### ISSUE TITLE
Plan the mailing system

### ISSUE THREAD

**Issue by VaradiTamas** [VaradiTamas/fahazfoglalo-weboldal#58]
**Description**

Now I have an implemented working email sending logic. The next task is to decide when to send emails and design them.

**Tasks**

- [x] Plan and decide when to send emails with what kind of data
- [x] Design these emails
- [x] Implement these emails
